port = 8443
tls = true

[paths]
"/expired/*" = ["expired.badssl.com:443"]
"/wrong-host/*" = ["wrong.host.badssl.com:443"]
"/self-signed/*" = ["self-signed.badssl.com:443"]
"/untrusted/*" = ["untrusted-root.badssl.com:443"]
"/revoked/*" = ["revoked.badssl.com:443"]
"/sha1/*" = ["sha1-intermediate.badssl.com:443"]
"/sha256/*" = ["sha256.badssl.com:443"]
"/ecc256/*" = ["ecc256.badssl.com:443"]
"/ecc384/*" = ["ecc384.badssl.com:443"]
"/rsa2048/*" = ["rsa2048.badssl.com:443"]
"/rsa4096/*" = ["rsa4096.badssl.com:443"]
"/rsa8192/*" = ["rsa8192.badssl.com:443"]
"/http/*" = ["http.badssl.com:80"]
"/tls-v1-0/*" = ["tls-v1-0.badssl.com:1010"]
"/tls-v1-1/*" = ["tls-v1-1.badssl.com:1011"]
"/tls-v1-2/*" = ["tls-v1-2.badssl.com:1012"]
"/no-common-name/*" = ["no-common-name.badssl.com:443"]
"/no-subject/*" = ["no-subject.badssl.com:443"]
"/incomplete-chain/*" = ["incomplete-chain.badssl.com:443"]
"/1000-sans/*" = ["1000-sans.badssl.com:443"]
"/dh480/*" = ["dh480.badssl.com:443"]
"/dh512/*" = ["dh512.badssl.com:443"]
"/dh1024/*" = ["dh1024.badssl.com:443"]
"/dh2048/*" = ["dh2048.badssl.com:443"]
"/null/*" = ["null.badssl.com:443"]
"/rc4/*" = ["rc4.badssl.com:443"]
"/rc4-md5/*" = ["rc4-md5.badssl.com:443"]
"/3des/*" = ["3des.badssl.com:443"]
"/hsts/*" = ["hsts.badssl.com:443"]
"/pinning/*" = ["pinning-test.badssl.com:443"]
"/long-domain/*" = ["long-extended-subdomain-name-containing-many-letters-and-dashes.badssl.com:443"]
