//! SQL statements for creating tables on each backend.
#[cfg(feature = "store-sqlite")]
pub const SQLITE_CREATE_TABLES: &[&str] = &[
    "CREATE TABLE IF NOT EXISTS api_key_usage (
        api_key             TEXT PRIMARY KEY,
        total_input_tokens  INTEGER NOT NULL DEFAULT 0,
        total_output_tokens INTEGER NOT NULL DEFAULT 0,
        total_cost          REAL NOT NULL DEFAULT 0.0,
        updated_at          TEXT NOT NULL DEFAULT (datetime('now'))
    )",
    "CREATE TABLE IF NOT EXISTS model_pricing (
        model_name          TEXT PRIMARY KEY,
        input_cost_per_1k   REAL NOT NULL,
        output_cost_per_1k  REAL NOT NULL,
        updated_at          TEXT NOT NULL DEFAULT (datetime('now'))
    )",
    "CREATE TABLE IF NOT EXISTS virtual_keys (
        key_hash            TEXT PRIMARY KEY,
        project_id          TEXT NOT NULL,
        name                TEXT NOT NULL,
        provider_name       TEXT NOT NULL,
        budget_limit        REAL,
        budget_duration     TEXT,
        budget_window_start INTEGER,
        rpm_limit           INTEGER,
        tpm_limit           INTEGER,
        allowed_models      TEXT,
        timeout_secs        INTEGER,
        tool_approval_mode  TEXT,
        allowed_tools       TEXT,
        active              INTEGER NOT NULL DEFAULT 1,
        created_at          TEXT NOT NULL DEFAULT (datetime('now')),
        expires_at          TEXT
    )",
    "CREATE TABLE IF NOT EXISTS api_key_model_usage (
        api_key             TEXT NOT NULL,
        model               TEXT NOT NULL,
        total_input_tokens  INTEGER NOT NULL DEFAULT 0,
        total_output_tokens INTEGER NOT NULL DEFAULT 0,
        total_cost          REAL NOT NULL DEFAULT 0.0,
        updated_at          TEXT NOT NULL DEFAULT (datetime('now')),
        PRIMARY KEY (api_key, model)
    )",
    "CREATE TABLE IF NOT EXISTS request_log (
        id                  INTEGER PRIMARY KEY AUTOINCREMENT,
        timestamp_unix      INTEGER NOT NULL,
        api_key             TEXT NOT NULL,
        project_id          TEXT,
        session_id          TEXT,
        metadata_json       TEXT,
        custom_cost_json    TEXT,
        custom_cost_applied INTEGER NOT NULL DEFAULT 0,
        provider_name       TEXT,
        prompt_name         TEXT,
        prompt_version      TEXT,
        prompt_environment  TEXT,
        model               TEXT,
        input_tokens        INTEGER NOT NULL DEFAULT 0,
        output_tokens       INTEGER NOT NULL DEFAULT 0,
        cost                REAL NOT NULL DEFAULT 0.0,
        is_streaming        INTEGER NOT NULL DEFAULT 0,
        safety_mode         TEXT,
        safety_matches      TEXT,
        semantic_policy_version TEXT,
        semantic_index_state    TEXT,
        semantic_degraded_reason TEXT,
        semantic_findings       TEXT,
        tool_trace          TEXT
    )",
    "CREATE INDEX IF NOT EXISTS idx_request_log_api_key ON request_log(api_key)",
    "CREATE INDEX IF NOT EXISTS idx_request_log_timestamp ON request_log(timestamp_unix)",
    "CREATE INDEX IF NOT EXISTS idx_request_log_project_id ON request_log(project_id)",
    "CREATE INDEX IF NOT EXISTS idx_request_log_session_id ON request_log(session_id)",
    "CREATE TABLE IF NOT EXISTS session_state (
        session_id          TEXT PRIMARY KEY,
        project_id          TEXT,
        project_ids_json    TEXT,
        first_request_unix  INTEGER,
        last_request_unix   INTEGER,
        updated_at_unix     INTEGER NOT NULL DEFAULT 0,
        request_count       INTEGER NOT NULL DEFAULT 0,
        streaming_request_count INTEGER NOT NULL DEFAULT 0,
        total_input_tokens  INTEGER NOT NULL DEFAULT 0,
        total_output_tokens INTEGER NOT NULL DEFAULT 0,
        total_cost          REAL NOT NULL DEFAULT 0.0,
        providers_json      TEXT,
        models_json         TEXT,
        prompt_names_json   TEXT,
        prompt_versions_json TEXT,
        tool_names_json     TEXT,
        latest_request_json TEXT,
        safety_event_count  INTEGER NOT NULL DEFAULT 0,
        semantic_event_count INTEGER NOT NULL DEFAULT 0,
        semantic_degraded_count INTEGER NOT NULL DEFAULT 0,
        tool_call_count     INTEGER NOT NULL DEFAULT 0,
        tool_error_count    INTEGER NOT NULL DEFAULT 0,
        status              TEXT,
        owner_id            TEXT,
        owner_acquired_at_unix INTEGER,
        last_transition_at_unix INTEGER,
        last_transition_reason TEXT,
        last_heartbeat_unix INTEGER,
        lease_expires_at_unix INTEGER,
        cancel_requested_at_unix INTEGER,
        cancel_requested_by TEXT,
        cancel_reason TEXT,
        handoff_target_owner_id TEXT,
        handoff_requested_at_unix INTEGER,
        handoff_reason TEXT,
        state_json          TEXT,
        metadata_json       TEXT
    )",
    "CREATE INDEX IF NOT EXISTS idx_session_state_project_id ON session_state(project_id)",
    "CREATE INDEX IF NOT EXISTS idx_session_state_last_request ON session_state(last_request_unix)",
    "CREATE TABLE IF NOT EXISTS session_event (
        event_seq           INTEGER PRIMARY KEY AUTOINCREMENT,
        session_id          TEXT NOT NULL,
        project_id          TEXT,
        event_kind          TEXT NOT NULL,
        actor_id            TEXT,
        reason              TEXT,
        payload_json        TEXT,
        created_at_unix     INTEGER NOT NULL
    )",
    "CREATE INDEX IF NOT EXISTS idx_session_event_session_seq ON session_event(session_id, event_seq)",
    "CREATE INDEX IF NOT EXISTS idx_session_event_created_at ON session_event(created_at_unix)",
    "CREATE TABLE IF NOT EXISTS project_policies (
        project_id          TEXT PRIMARY KEY,
        budget_limit        REAL,
        budget_duration     TEXT,
        rpm_limit           INTEGER,
        tpm_limit           INTEGER,
        fallback_order      TEXT,
        adaptive_enabled    INTEGER NOT NULL DEFAULT 1,
        timeout_secs        INTEGER,
        provider_rpm_limits TEXT,
        provider_tpm_limits TEXT,
        provider_timeouts   TEXT,
        provider_input_costs TEXT,
        provider_output_costs TEXT,
        semantic_cache_enabled INTEGER,
        semantic_cache_ttl_secs INTEGER,
        semantic_cache_similarity_threshold REAL,
        tool_approval_mode  TEXT,
        allowed_tools       TEXT,
        updated_at          TEXT NOT NULL DEFAULT (datetime('now'))
    )",
    "CREATE TABLE IF NOT EXISTS managed_providers (
        name                TEXT PRIMARY KEY,
        enabled             INTEGER NOT NULL DEFAULT 1,
        api_key_env         TEXT,
        base_url            TEXT,
        models_json         TEXT,
        api_key_header      TEXT,
        timeout_secs        INTEGER,
        family              TEXT,
        surfaces_json       TEXT,
        routing_metadata_json TEXT,
        created_at          TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at          TEXT NOT NULL DEFAULT (datetime('now'))
    )",
    "CREATE TABLE IF NOT EXISTS routing_rules (
        rule_id             TEXT PRIMARY KEY,
        project_id          TEXT NOT NULL,
        name                TEXT NOT NULL,
        priority            INTEGER NOT NULL DEFAULT 0,
        enabled             INTEGER NOT NULL DEFAULT 1,
        match_path          TEXT,
        match_model         TEXT,
        match_streaming     INTEGER,
        match_role          TEXT,
        match_headers       TEXT,
        min_prompt_tokens   INTEGER,
        max_prompt_tokens   INTEGER,
        deny_reason         TEXT,
        provider_order      TEXT,
        provider_weights    TEXT,
        timeout_secs        INTEGER,
        created_at          TEXT NOT NULL DEFAULT (datetime('now'))
    )",
    "CREATE INDEX IF NOT EXISTS idx_routing_rules_project_id ON routing_rules(project_id)",
    "CREATE TABLE IF NOT EXISTS safety_policies (
        project_id          TEXT PRIMARY KEY,
        mode                TEXT NOT NULL,
        rules_json          TEXT,
        updated_at          TEXT NOT NULL DEFAULT (datetime('now'))
    )",
    "CREATE TABLE IF NOT EXISTS semantic_policies (
        project_id          TEXT PRIMARY KEY,
        version             TEXT NOT NULL,
        enabled             INTEGER NOT NULL DEFAULT 1,
        entities_json       TEXT,
        topics_json         TEXT,
        updated_at          TEXT NOT NULL DEFAULT (datetime('now'))
    )",
    "CREATE TABLE IF NOT EXISTS prompt_cache_routes (
        route_id            TEXT PRIMARY KEY,
        project_id          TEXT NOT NULL,
        cache_key           TEXT NOT NULL,
        provider_name       TEXT NOT NULL,
        signal_kind         TEXT NOT NULL DEFAULT 'warm',
        signal_strength     REAL NOT NULL DEFAULT 1.0,
        observed_at_ms      INTEGER NOT NULL DEFAULT 0,
        expires_at_ms       INTEGER NOT NULL
    )",
    "CREATE INDEX IF NOT EXISTS idx_prompt_cache_routes_expires_at ON prompt_cache_routes(expires_at_ms)",
    "CREATE TABLE IF NOT EXISTS semantic_cache_entries (
        cache_id            TEXT PRIMARY KEY,
        project_id          TEXT NOT NULL,
        provider_name       TEXT NOT NULL,
        model               TEXT NOT NULL,
        tokens_json         TEXT NOT NULL,
        response_status     INTEGER NOT NULL,
        content_type        TEXT,
        response_body       BLOB NOT NULL,
        prompt_tokens       INTEGER NOT NULL DEFAULT 0,
        created_at_ms       INTEGER NOT NULL,
        expires_at_ms       INTEGER NOT NULL
    )",
    "CREATE INDEX IF NOT EXISTS idx_semantic_cache_entries_expires_at ON semantic_cache_entries(expires_at_ms)",
    "CREATE INDEX IF NOT EXISTS idx_semantic_cache_entries_created_at ON semantic_cache_entries(created_at_ms)",
    "CREATE TABLE IF NOT EXISTS project_tools (
        project_id          TEXT NOT NULL,
        tool_name           TEXT NOT NULL,
        description         TEXT,
        input_schema_json   TEXT NOT NULL,
        executor_kind       TEXT NOT NULL,
        executor_config_json TEXT,
        enabled             INTEGER NOT NULL DEFAULT 1,
        timeout_ms          INTEGER,
        updated_at          TEXT NOT NULL DEFAULT (datetime('now')),
        PRIMARY KEY (project_id, tool_name)
    )",
    "CREATE INDEX IF NOT EXISTS idx_project_tools_project_id ON project_tools(project_id)",
    "CREATE TABLE IF NOT EXISTS project_prompts (
        project_id          TEXT NOT NULL,
        prompt_name         TEXT NOT NULL,
        version             TEXT NOT NULL,
        environment         TEXT NOT NULL,
        description         TEXT,
        target              TEXT NOT NULL,
        template_text       TEXT NOT NULL,
        variables_schema_json TEXT,
        rollout_metadata_json TEXT,
        active              INTEGER NOT NULL DEFAULT 1,
        updated_at          TEXT NOT NULL DEFAULT (datetime('now')),
        PRIMARY KEY (project_id, prompt_name, version)
    )",
    "CREATE INDEX IF NOT EXISTS idx_project_prompts_project_id ON project_prompts(project_id)",
    "CREATE INDEX IF NOT EXISTS idx_project_prompts_name ON project_prompts(project_id, prompt_name)",
    "CREATE TABLE IF NOT EXISTS project_rollout_policies (
        project_id          TEXT NOT NULL,
        policy_name         TEXT NOT NULL,
        description         TEXT,
        gate_config_json    TEXT NOT NULL,
        target_environment  TEXT,
        updated_at          TEXT NOT NULL DEFAULT (datetime('now')),
        PRIMARY KEY (project_id, policy_name)
    )",
    "CREATE INDEX IF NOT EXISTS idx_project_rollout_policies_project_id ON project_rollout_policies(project_id)",
    "CREATE TABLE IF NOT EXISTS project_prompt_rollouts (
        project_id          TEXT NOT NULL,
        prompt_name         TEXT NOT NULL,
        rollout_id          TEXT NOT NULL,
        policy_name         TEXT NOT NULL,
        baseline_version    TEXT,
        candidate_version   TEXT NOT NULL,
        baseline_run_id     TEXT NOT NULL,
        candidate_run_id    TEXT NOT NULL,
        target_environment  TEXT,
        status              TEXT NOT NULL,
        recommendation_action TEXT,
        comparison_json     TEXT NOT NULL,
        created_at          TEXT NOT NULL DEFAULT (datetime('now')),
        applied_at          TEXT,
        PRIMARY KEY (project_id, prompt_name, rollout_id)
    )",
    "CREATE INDEX IF NOT EXISTS idx_project_prompt_rollouts_prompt ON project_prompt_rollouts(project_id, prompt_name)",
    "CREATE TABLE IF NOT EXISTS project_datasets (
        project_id          TEXT NOT NULL,
        dataset_name        TEXT NOT NULL,
        description         TEXT,
        schema_json         TEXT,
        updated_at          TEXT NOT NULL DEFAULT (datetime('now')),
        PRIMARY KEY (project_id, dataset_name)
    )",
    "CREATE INDEX IF NOT EXISTS idx_project_datasets_project_id ON project_datasets(project_id)",
    "CREATE TABLE IF NOT EXISTS project_dataset_items (
        project_id          TEXT NOT NULL,
        dataset_name        TEXT NOT NULL,
        item_id             TEXT NOT NULL,
        input_json          TEXT NOT NULL,
        expected_output_json TEXT,
        metadata_json       TEXT,
        updated_at          TEXT NOT NULL DEFAULT (datetime('now')),
        PRIMARY KEY (project_id, dataset_name, item_id)
    )",
    "CREATE INDEX IF NOT EXISTS idx_project_dataset_items_dataset ON project_dataset_items(project_id, dataset_name)",
    "CREATE TABLE IF NOT EXISTS project_eval_runs (
        run_id               TEXT PRIMARY KEY,
        project_id           TEXT NOT NULL,
        dataset_name         TEXT NOT NULL,
        target_url           TEXT NOT NULL,
        status               TEXT NOT NULL,
        total_items          INTEGER NOT NULL DEFAULT 0,
        passed_items         INTEGER NOT NULL DEFAULT 0,
        failed_items         INTEGER NOT NULL DEFAULT 0,
        total_input_tokens   INTEGER NOT NULL DEFAULT 0,
        total_output_tokens  INTEGER NOT NULL DEFAULT 0,
        total_cost           REAL NOT NULL DEFAULT 0.0,
        average_latency_ms   REAL NOT NULL DEFAULT 0.0,
        summary_json         TEXT,
        created_at           TEXT NOT NULL DEFAULT (datetime('now')),
        completed_at         TEXT
    )",
    "CREATE INDEX IF NOT EXISTS idx_project_eval_runs_project_id ON project_eval_runs(project_id)",
    "CREATE INDEX IF NOT EXISTS idx_project_eval_runs_dataset ON project_eval_runs(project_id, dataset_name)",
    "CREATE TABLE IF NOT EXISTS project_eval_run_items (
        run_id               TEXT NOT NULL,
        project_id           TEXT NOT NULL,
        dataset_name         TEXT NOT NULL,
        item_id              TEXT NOT NULL,
        passed               INTEGER NOT NULL DEFAULT 0,
        status_code          INTEGER,
        latency_ms           INTEGER NOT NULL DEFAULT 0,
        output_text          TEXT,
        evaluation_json      TEXT,
        error                TEXT,
        input_tokens         INTEGER NOT NULL DEFAULT 0,
        output_tokens        INTEGER NOT NULL DEFAULT 0,
        cost                 REAL NOT NULL DEFAULT 0.0,
        created_at           TEXT NOT NULL DEFAULT (datetime('now')),
        PRIMARY KEY (run_id, item_id)
    )",
    "CREATE INDEX IF NOT EXISTS idx_project_eval_run_items_run_id ON project_eval_run_items(project_id, run_id)",
    "CREATE TABLE IF NOT EXISTS governance_history (
        change_id           TEXT PRIMARY KEY,
        project_id          TEXT NOT NULL,
        resource_type       TEXT NOT NULL,
        resource_id         TEXT NOT NULL,
        action              TEXT NOT NULL,
        before_json         TEXT,
        after_json          TEXT,
        changed_at          TEXT NOT NULL DEFAULT (datetime('now'))
    )",
    "CREATE INDEX IF NOT EXISTS idx_governance_history_project_id ON governance_history(project_id)",
    "CREATE INDEX IF NOT EXISTS idx_governance_history_resource_type ON governance_history(project_id, resource_type)",
];

#[cfg(feature = "store-postgres")]
pub const POSTGRES_CREATE_TABLES: &[&str] = &[
    "CREATE TABLE IF NOT EXISTS api_key_usage (
        api_key             TEXT PRIMARY KEY,
        total_input_tokens  BIGINT NOT NULL DEFAULT 0,
        total_output_tokens BIGINT NOT NULL DEFAULT 0,
        total_cost          DOUBLE PRECISION NOT NULL DEFAULT 0.0,
        updated_at          TEXT NOT NULL DEFAULT ((EXTRACT(EPOCH FROM now()))::BIGINT::TEXT)
    )",
    "CREATE TABLE IF NOT EXISTS model_pricing (
        model_name          TEXT PRIMARY KEY,
        input_cost_per_1k   DOUBLE PRECISION NOT NULL,
        output_cost_per_1k  DOUBLE PRECISION NOT NULL,
        updated_at          TEXT NOT NULL DEFAULT ((EXTRACT(EPOCH FROM now()))::BIGINT::TEXT)
    )",
    "CREATE TABLE IF NOT EXISTS virtual_keys (
        key_hash            TEXT PRIMARY KEY,
        project_id          TEXT NOT NULL,
        name                TEXT NOT NULL,
        provider_name       TEXT NOT NULL,
        budget_limit        DOUBLE PRECISION,
        budget_duration     TEXT,
        budget_window_start BIGINT,
        rpm_limit           INTEGER,
        tpm_limit           INTEGER,
        allowed_models      TEXT,
        timeout_secs        BIGINT,
        tool_approval_mode  TEXT,
        allowed_tools       TEXT,
        active              BOOLEAN NOT NULL DEFAULT TRUE,
        created_at          TEXT NOT NULL DEFAULT ((EXTRACT(EPOCH FROM now()))::BIGINT::TEXT),
        expires_at          TEXT
    )",
    "CREATE TABLE IF NOT EXISTS api_key_model_usage (
        api_key             TEXT NOT NULL,
        model               TEXT NOT NULL,
        total_input_tokens  BIGINT NOT NULL DEFAULT 0,
        total_output_tokens BIGINT NOT NULL DEFAULT 0,
        total_cost          DOUBLE PRECISION NOT NULL DEFAULT 0.0,
        updated_at          TEXT NOT NULL DEFAULT ((EXTRACT(EPOCH FROM now()))::BIGINT::TEXT),
        PRIMARY KEY (api_key, model)
    )",
    "CREATE TABLE IF NOT EXISTS request_log (
        id                  BIGSERIAL PRIMARY KEY,
        timestamp_unix      BIGINT NOT NULL,
        api_key             TEXT NOT NULL,
        project_id          TEXT,
        session_id          TEXT,
        metadata_json       TEXT,
        custom_cost_json    TEXT,
        custom_cost_applied BOOLEAN NOT NULL DEFAULT FALSE,
        provider_name       TEXT,
        prompt_name         TEXT,
        prompt_version      TEXT,
        prompt_environment  TEXT,
        model               TEXT,
        input_tokens        BIGINT NOT NULL DEFAULT 0,
        output_tokens       BIGINT NOT NULL DEFAULT 0,
        cost                DOUBLE PRECISION NOT NULL DEFAULT 0.0,
        is_streaming        BOOLEAN NOT NULL DEFAULT FALSE,
        safety_mode         TEXT,
        safety_matches      TEXT,
        semantic_policy_version TEXT,
        semantic_index_state    TEXT,
        semantic_degraded_reason TEXT,
        semantic_findings       TEXT,
        tool_trace          TEXT
    )",
    "CREATE INDEX IF NOT EXISTS idx_request_log_api_key ON request_log(api_key)",
    "CREATE INDEX IF NOT EXISTS idx_request_log_timestamp ON request_log(timestamp_unix)",
    "CREATE INDEX IF NOT EXISTS idx_request_log_project_id ON request_log(project_id)",
    "CREATE INDEX IF NOT EXISTS idx_request_log_session_id ON request_log(session_id)",
    "CREATE TABLE IF NOT EXISTS session_state (
        session_id          TEXT PRIMARY KEY,
        project_id          TEXT,
        project_ids_json    TEXT,
        first_request_unix  BIGINT,
        last_request_unix   BIGINT,
        updated_at_unix     BIGINT NOT NULL DEFAULT 0,
        request_count       BIGINT NOT NULL DEFAULT 0,
        streaming_request_count BIGINT NOT NULL DEFAULT 0,
        total_input_tokens  BIGINT NOT NULL DEFAULT 0,
        total_output_tokens BIGINT NOT NULL DEFAULT 0,
        total_cost          DOUBLE PRECISION NOT NULL DEFAULT 0.0,
        providers_json      TEXT,
        models_json         TEXT,
        prompt_names_json   TEXT,
        prompt_versions_json TEXT,
        tool_names_json     TEXT,
        latest_request_json TEXT,
        safety_event_count  BIGINT NOT NULL DEFAULT 0,
        semantic_event_count BIGINT NOT NULL DEFAULT 0,
        semantic_degraded_count BIGINT NOT NULL DEFAULT 0,
        tool_call_count     BIGINT NOT NULL DEFAULT 0,
        tool_error_count    BIGINT NOT NULL DEFAULT 0,
        status              TEXT,
        owner_id            TEXT,
        owner_acquired_at_unix BIGINT,
        last_transition_at_unix BIGINT,
        last_transition_reason TEXT,
        last_heartbeat_unix BIGINT,
        lease_expires_at_unix BIGINT,
        cancel_requested_at_unix BIGINT,
        cancel_requested_by TEXT,
        cancel_reason TEXT,
        handoff_target_owner_id TEXT,
        handoff_requested_at_unix BIGINT,
        handoff_reason TEXT,
        state_json          TEXT,
        metadata_json       TEXT
    )",
    "CREATE INDEX IF NOT EXISTS idx_session_state_project_id ON session_state(project_id)",
    "CREATE INDEX IF NOT EXISTS idx_session_state_last_request ON session_state(last_request_unix)",
    "CREATE TABLE IF NOT EXISTS session_event (
        event_seq           BIGSERIAL PRIMARY KEY,
        session_id          TEXT NOT NULL,
        project_id          TEXT,
        event_kind          TEXT NOT NULL,
        actor_id            TEXT,
        reason              TEXT,
        payload_json        TEXT,
        created_at_unix     BIGINT NOT NULL
    )",
    "CREATE INDEX IF NOT EXISTS idx_session_event_session_seq ON session_event(session_id, event_seq)",
    "CREATE INDEX IF NOT EXISTS idx_session_event_created_at ON session_event(created_at_unix)",
    "CREATE TABLE IF NOT EXISTS project_policies (
        project_id          TEXT PRIMARY KEY,
        budget_limit        DOUBLE PRECISION,
        budget_duration     TEXT,
        rpm_limit           INTEGER,
        tpm_limit           INTEGER,
        fallback_order      TEXT,
        adaptive_enabled    BOOLEAN NOT NULL DEFAULT TRUE,
        timeout_secs        BIGINT,
        provider_rpm_limits TEXT,
        provider_tpm_limits TEXT,
        provider_timeouts   TEXT,
        provider_input_costs TEXT,
        provider_output_costs TEXT,
        semantic_cache_enabled BOOLEAN,
        semantic_cache_ttl_secs BIGINT,
        semantic_cache_similarity_threshold DOUBLE PRECISION,
        tool_approval_mode  TEXT,
        allowed_tools       TEXT,
        updated_at          TEXT NOT NULL DEFAULT ((EXTRACT(EPOCH FROM now()))::BIGINT::TEXT)
    )",
    "CREATE TABLE IF NOT EXISTS managed_providers (
        name                TEXT PRIMARY KEY,
        enabled             BOOLEAN NOT NULL DEFAULT TRUE,
        api_key_env         TEXT,
        base_url            TEXT,
        models_json         TEXT,
        api_key_header      TEXT,
        timeout_secs        BIGINT,
        family              TEXT,
        surfaces_json       TEXT,
        routing_metadata_json TEXT,
        created_at          TEXT NOT NULL DEFAULT ((EXTRACT(EPOCH FROM now()))::BIGINT::TEXT),
        updated_at          TEXT NOT NULL DEFAULT ((EXTRACT(EPOCH FROM now()))::BIGINT::TEXT)
    )",
    "CREATE TABLE IF NOT EXISTS routing_rules (
        rule_id             TEXT PRIMARY KEY,
        project_id          TEXT NOT NULL,
        name                TEXT NOT NULL,
        priority            INTEGER NOT NULL DEFAULT 0,
        enabled             BOOLEAN NOT NULL DEFAULT TRUE,
        match_path          TEXT,
        match_model         TEXT,
        match_streaming     BOOLEAN,
        match_role          TEXT,
        match_headers       TEXT,
        min_prompt_tokens   INTEGER,
        max_prompt_tokens   INTEGER,
        deny_reason         TEXT,
        provider_order      TEXT,
        provider_weights    TEXT,
        timeout_secs        BIGINT,
        created_at          TEXT NOT NULL DEFAULT ((EXTRACT(EPOCH FROM now()))::BIGINT::TEXT)
    )",
    "CREATE INDEX IF NOT EXISTS idx_routing_rules_project_id ON routing_rules(project_id)",
    "CREATE TABLE IF NOT EXISTS safety_policies (
        project_id          TEXT PRIMARY KEY,
        mode                TEXT NOT NULL,
        rules_json          TEXT,
        updated_at          TEXT NOT NULL DEFAULT ((EXTRACT(EPOCH FROM now()))::BIGINT::TEXT)
    )",
    "CREATE TABLE IF NOT EXISTS semantic_policies (
        project_id          TEXT PRIMARY KEY,
        version             TEXT NOT NULL,
        enabled             BOOLEAN NOT NULL DEFAULT TRUE,
        entities_json       TEXT,
        topics_json         TEXT,
        updated_at          TEXT NOT NULL DEFAULT ((EXTRACT(EPOCH FROM now()))::BIGINT::TEXT)
    )",
    "CREATE TABLE IF NOT EXISTS prompt_cache_routes (
        route_id            TEXT PRIMARY KEY,
        project_id          TEXT NOT NULL,
        cache_key           TEXT NOT NULL,
        provider_name       TEXT NOT NULL,
        signal_kind         TEXT NOT NULL DEFAULT 'warm',
        signal_strength     DOUBLE PRECISION NOT NULL DEFAULT 1.0,
        observed_at_ms      BIGINT NOT NULL DEFAULT 0,
        expires_at_ms       BIGINT NOT NULL
    )",
    "CREATE INDEX IF NOT EXISTS idx_prompt_cache_routes_expires_at ON prompt_cache_routes(expires_at_ms)",
    "CREATE TABLE IF NOT EXISTS semantic_cache_entries (
        cache_id            TEXT PRIMARY KEY,
        project_id          TEXT NOT NULL,
        provider_name       TEXT NOT NULL,
        model               TEXT NOT NULL,
        tokens_json         TEXT NOT NULL,
        response_status     INTEGER NOT NULL,
        content_type        TEXT,
        response_body       BYTEA NOT NULL,
        prompt_tokens       BIGINT NOT NULL DEFAULT 0,
        created_at_ms       BIGINT NOT NULL,
        expires_at_ms       BIGINT NOT NULL
    )",
    "CREATE INDEX IF NOT EXISTS idx_semantic_cache_entries_expires_at ON semantic_cache_entries(expires_at_ms)",
    "CREATE INDEX IF NOT EXISTS idx_semantic_cache_entries_created_at ON semantic_cache_entries(created_at_ms)",
    "CREATE TABLE IF NOT EXISTS project_tools (
        project_id          TEXT NOT NULL,
        tool_name           TEXT NOT NULL,
        description         TEXT,
        input_schema_json   TEXT NOT NULL,
        executor_kind       TEXT NOT NULL,
        executor_config_json TEXT,
        enabled             BOOLEAN NOT NULL DEFAULT TRUE,
        timeout_ms          BIGINT,
        updated_at          TEXT NOT NULL DEFAULT ((EXTRACT(EPOCH FROM now()))::BIGINT::TEXT),
        PRIMARY KEY (project_id, tool_name)
    )",
    "CREATE INDEX IF NOT EXISTS idx_project_tools_project_id ON project_tools(project_id)",
    "CREATE TABLE IF NOT EXISTS project_prompts (
        project_id          TEXT NOT NULL,
        prompt_name         TEXT NOT NULL,
        version             TEXT NOT NULL,
        environment         TEXT NOT NULL,
        description         TEXT,
        target              TEXT NOT NULL,
        template_text       TEXT NOT NULL,
        variables_schema_json TEXT,
        rollout_metadata_json TEXT,
        active              BOOLEAN NOT NULL DEFAULT TRUE,
        updated_at          TEXT NOT NULL DEFAULT ((EXTRACT(EPOCH FROM now()))::BIGINT::TEXT),
        PRIMARY KEY (project_id, prompt_name, version)
    )",
    "CREATE INDEX IF NOT EXISTS idx_project_prompts_project_id ON project_prompts(project_id)",
    "CREATE INDEX IF NOT EXISTS idx_project_prompts_name ON project_prompts(project_id, prompt_name)",
    "CREATE TABLE IF NOT EXISTS project_rollout_policies (
        project_id          TEXT NOT NULL,
        policy_name         TEXT NOT NULL,
        description         TEXT,
        gate_config_json    TEXT NOT NULL,
        target_environment  TEXT,
        updated_at          TEXT NOT NULL DEFAULT ((EXTRACT(EPOCH FROM now()))::BIGINT::TEXT),
        PRIMARY KEY (project_id, policy_name)
    )",
    "CREATE INDEX IF NOT EXISTS idx_project_rollout_policies_project_id ON project_rollout_policies(project_id)",
    "CREATE TABLE IF NOT EXISTS project_prompt_rollouts (
        project_id          TEXT NOT NULL,
        prompt_name         TEXT NOT NULL,
        rollout_id          TEXT NOT NULL,
        policy_name         TEXT NOT NULL,
        baseline_version    TEXT,
        candidate_version   TEXT NOT NULL,
        baseline_run_id     TEXT NOT NULL,
        candidate_run_id    TEXT NOT NULL,
        target_environment  TEXT,
        status              TEXT NOT NULL,
        recommendation_action TEXT,
        comparison_json     TEXT NOT NULL,
        created_at          TEXT NOT NULL DEFAULT ((EXTRACT(EPOCH FROM now()))::BIGINT::TEXT),
        applied_at          TEXT,
        PRIMARY KEY (project_id, prompt_name, rollout_id)
    )",
    "CREATE INDEX IF NOT EXISTS idx_project_prompt_rollouts_prompt ON project_prompt_rollouts(project_id, prompt_name)",
    "CREATE TABLE IF NOT EXISTS project_datasets (
        project_id          TEXT NOT NULL,
        dataset_name        TEXT NOT NULL,
        description         TEXT,
        schema_json         TEXT,
        updated_at          TEXT NOT NULL DEFAULT ((EXTRACT(EPOCH FROM now()))::BIGINT::TEXT),
        PRIMARY KEY (project_id, dataset_name)
    )",
    "CREATE INDEX IF NOT EXISTS idx_project_datasets_project_id ON project_datasets(project_id)",
    "CREATE TABLE IF NOT EXISTS project_dataset_items (
        project_id          TEXT NOT NULL,
        dataset_name        TEXT NOT NULL,
        item_id             TEXT NOT NULL,
        input_json          TEXT NOT NULL,
        expected_output_json TEXT,
        metadata_json       TEXT,
        updated_at          TEXT NOT NULL DEFAULT ((EXTRACT(EPOCH FROM now()))::BIGINT::TEXT),
        PRIMARY KEY (project_id, dataset_name, item_id)
    )",
    "CREATE INDEX IF NOT EXISTS idx_project_dataset_items_dataset ON project_dataset_items(project_id, dataset_name)",
    "CREATE TABLE IF NOT EXISTS project_eval_runs (
        run_id               TEXT PRIMARY KEY,
        project_id           TEXT NOT NULL,
        dataset_name         TEXT NOT NULL,
        target_url           TEXT NOT NULL,
        status               TEXT NOT NULL,
        total_items          INTEGER NOT NULL DEFAULT 0,
        passed_items         INTEGER NOT NULL DEFAULT 0,
        failed_items         INTEGER NOT NULL DEFAULT 0,
        total_input_tokens   BIGINT NOT NULL DEFAULT 0,
        total_output_tokens  BIGINT NOT NULL DEFAULT 0,
        total_cost           DOUBLE PRECISION NOT NULL DEFAULT 0.0,
        average_latency_ms   DOUBLE PRECISION NOT NULL DEFAULT 0.0,
        summary_json         TEXT,
        created_at           TEXT NOT NULL DEFAULT ((EXTRACT(EPOCH FROM now()))::BIGINT::TEXT),
        completed_at         TEXT
    )",
    "CREATE INDEX IF NOT EXISTS idx_project_eval_runs_project_id ON project_eval_runs(project_id)",
    "CREATE INDEX IF NOT EXISTS idx_project_eval_runs_dataset ON project_eval_runs(project_id, dataset_name)",
    "CREATE TABLE IF NOT EXISTS project_eval_run_items (
        run_id               TEXT NOT NULL,
        project_id           TEXT NOT NULL,
        dataset_name         TEXT NOT NULL,
        item_id              TEXT NOT NULL,
        passed               BOOLEAN NOT NULL DEFAULT FALSE,
        status_code          INTEGER,
        latency_ms           BIGINT NOT NULL DEFAULT 0,
        output_text          TEXT,
        evaluation_json      TEXT,
        error                TEXT,
        input_tokens         BIGINT NOT NULL DEFAULT 0,
        output_tokens        BIGINT NOT NULL DEFAULT 0,
        cost                 DOUBLE PRECISION NOT NULL DEFAULT 0.0,
        created_at           TEXT NOT NULL DEFAULT ((EXTRACT(EPOCH FROM now()))::BIGINT::TEXT),
        PRIMARY KEY (run_id, item_id)
    )",
    "CREATE INDEX IF NOT EXISTS idx_project_eval_run_items_run_id ON project_eval_run_items(project_id, run_id)",
    "CREATE TABLE IF NOT EXISTS governance_history (
        change_id           TEXT PRIMARY KEY,
        project_id          TEXT NOT NULL,
        resource_type       TEXT NOT NULL,
        resource_id         TEXT NOT NULL,
        action              TEXT NOT NULL,
        before_json         TEXT,
        after_json          TEXT,
        changed_at          TEXT NOT NULL DEFAULT ((EXTRACT(EPOCH FROM now()))::BIGINT::TEXT)
    )",
    "CREATE INDEX IF NOT EXISTS idx_governance_history_project_id ON governance_history(project_id)",
    "CREATE INDEX IF NOT EXISTS idx_governance_history_resource_type ON governance_history(project_id, resource_type)",
];

#[cfg(feature = "store-mysql")]
pub const MYSQL_CREATE_TABLES: &[&str] = &[
    "CREATE TABLE IF NOT EXISTS api_key_usage (
        api_key             VARCHAR(255) PRIMARY KEY,
        total_input_tokens  BIGINT NOT NULL DEFAULT 0,
        total_output_tokens BIGINT NOT NULL DEFAULT 0,
        total_cost          DOUBLE NOT NULL DEFAULT 0.0,
        updated_at          VARCHAR(32) NOT NULL DEFAULT (CAST(UNIX_TIMESTAMP() AS CHAR))
    )",
    "CREATE TABLE IF NOT EXISTS model_pricing (
        model_name          VARCHAR(255) PRIMARY KEY,
        input_cost_per_1k   DOUBLE NOT NULL,
        output_cost_per_1k  DOUBLE NOT NULL,
        updated_at          VARCHAR(32) NOT NULL DEFAULT (CAST(UNIX_TIMESTAMP() AS CHAR))
    )",
    "CREATE TABLE IF NOT EXISTS virtual_keys (
        key_hash            VARCHAR(255) PRIMARY KEY,
        project_id          VARCHAR(255) NOT NULL,
        name                VARCHAR(255) NOT NULL,
        provider_name       VARCHAR(255) NOT NULL,
        budget_limit        DOUBLE,
        budget_duration     VARCHAR(32),
        budget_window_start BIGINT,
        rpm_limit           INT,
        tpm_limit           INT,
        allowed_models      TEXT,
        timeout_secs        BIGINT,
        tool_approval_mode  TEXT,
        allowed_tools       TEXT,
        active              BOOLEAN NOT NULL DEFAULT TRUE,
        created_at          VARCHAR(32) NOT NULL DEFAULT (CAST(UNIX_TIMESTAMP() AS CHAR)),
        expires_at          VARCHAR(32) NULL
    )",
    "CREATE TABLE IF NOT EXISTS api_key_model_usage (
        api_key             VARCHAR(255) NOT NULL,
        model               VARCHAR(255) NOT NULL,
        total_input_tokens  BIGINT NOT NULL DEFAULT 0,
        total_output_tokens BIGINT NOT NULL DEFAULT 0,
        total_cost          DOUBLE NOT NULL DEFAULT 0.0,
        updated_at          VARCHAR(32) NOT NULL DEFAULT (CAST(UNIX_TIMESTAMP() AS CHAR)),
        PRIMARY KEY (api_key, model)
    )",
    "CREATE TABLE IF NOT EXISTS request_log (
        id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
        timestamp_unix      BIGINT NOT NULL,
        api_key             VARCHAR(255) NOT NULL,
        project_id          VARCHAR(255),
        session_id          VARCHAR(255),
        metadata_json       TEXT,
        custom_cost_json    TEXT,
        custom_cost_applied BOOLEAN NOT NULL DEFAULT FALSE,
        provider_name       VARCHAR(255),
        prompt_name         VARCHAR(255),
        prompt_version      VARCHAR(255),
        prompt_environment  VARCHAR(255),
        model               VARCHAR(255),
        input_tokens        BIGINT NOT NULL DEFAULT 0,
        output_tokens       BIGINT NOT NULL DEFAULT 0,
        cost                DOUBLE NOT NULL DEFAULT 0.0,
        is_streaming        BOOLEAN NOT NULL DEFAULT FALSE,
        safety_mode         VARCHAR(64),
        safety_matches      TEXT,
        semantic_policy_version VARCHAR(255),
        semantic_index_state VARCHAR(64),
        semantic_degraded_reason TEXT,
        semantic_findings   TEXT,
        tool_trace          TEXT,
        INDEX idx_request_log_api_key (api_key),
        INDEX idx_request_log_timestamp (timestamp_unix),
        INDEX idx_request_log_project_id (project_id),
        INDEX idx_request_log_session_id (session_id)
    )",
    "CREATE TABLE IF NOT EXISTS session_state (
        session_id          VARCHAR(255) PRIMARY KEY,
        project_id          VARCHAR(255),
        project_ids_json    TEXT,
        first_request_unix  BIGINT NULL,
        last_request_unix   BIGINT NULL,
        updated_at_unix     BIGINT NOT NULL DEFAULT 0,
        request_count       BIGINT NOT NULL DEFAULT 0,
        streaming_request_count BIGINT NOT NULL DEFAULT 0,
        total_input_tokens  BIGINT NOT NULL DEFAULT 0,
        total_output_tokens BIGINT NOT NULL DEFAULT 0,
        total_cost          DOUBLE NOT NULL DEFAULT 0.0,
        providers_json      TEXT,
        models_json         TEXT,
        prompt_names_json   TEXT,
        prompt_versions_json TEXT,
        tool_names_json     TEXT,
        latest_request_json TEXT,
        safety_event_count  BIGINT NOT NULL DEFAULT 0,
        semantic_event_count BIGINT NOT NULL DEFAULT 0,
        semantic_degraded_count BIGINT NOT NULL DEFAULT 0,
        tool_call_count     BIGINT NOT NULL DEFAULT 0,
        tool_error_count    BIGINT NOT NULL DEFAULT 0,
        status              VARCHAR(64),
        owner_id            VARCHAR(255) NULL,
        owner_acquired_at_unix BIGINT NULL,
        last_transition_at_unix BIGINT NULL,
        last_transition_reason TEXT NULL,
        last_heartbeat_unix BIGINT NULL,
        lease_expires_at_unix BIGINT NULL,
        cancel_requested_at_unix BIGINT NULL,
        cancel_requested_by TEXT NULL,
        cancel_reason TEXT NULL,
        handoff_target_owner_id VARCHAR(255) NULL,
        handoff_requested_at_unix BIGINT NULL,
        handoff_reason TEXT NULL,
        state_json          LONGTEXT,
        metadata_json       LONGTEXT,
        INDEX idx_session_state_project_id (project_id),
        INDEX idx_session_state_last_request (last_request_unix)
    )",
    "CREATE TABLE IF NOT EXISTS session_event (
        event_seq           BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        session_id          VARCHAR(255) NOT NULL,
        project_id          VARCHAR(255) NULL,
        event_kind          VARCHAR(255) NOT NULL,
        actor_id            VARCHAR(255) NULL,
        reason              TEXT NULL,
        payload_json        LONGTEXT NULL,
        created_at_unix     BIGINT NOT NULL,
        INDEX idx_session_event_session_seq (session_id, event_seq),
        INDEX idx_session_event_created_at (created_at_unix)
    )",
    "CREATE TABLE IF NOT EXISTS project_policies (
        project_id          VARCHAR(255) PRIMARY KEY,
        budget_limit        DOUBLE,
        budget_duration     VARCHAR(64),
        rpm_limit           INT,
        tpm_limit           INT,
        fallback_order      TEXT,
        adaptive_enabled    BOOLEAN NOT NULL DEFAULT TRUE,
        timeout_secs        BIGINT,
        provider_rpm_limits TEXT,
        provider_tpm_limits TEXT,
        provider_timeouts   TEXT,
        provider_input_costs TEXT,
        provider_output_costs TEXT,
        semantic_cache_enabled BOOLEAN,
        semantic_cache_ttl_secs BIGINT,
        semantic_cache_similarity_threshold DOUBLE,
        tool_approval_mode  TEXT,
        allowed_tools       TEXT,
        updated_at          VARCHAR(32) NOT NULL DEFAULT (CAST(UNIX_TIMESTAMP() AS CHAR))
    )",
    "CREATE TABLE IF NOT EXISTS managed_providers (
        name                VARCHAR(255) PRIMARY KEY,
        enabled             BOOLEAN NOT NULL DEFAULT TRUE,
        api_key_env         VARCHAR(255) NULL,
        base_url            TEXT NULL,
        models_json         LONGTEXT NULL,
        api_key_header      TEXT NULL,
        timeout_secs        BIGINT NULL,
        family              VARCHAR(64) NULL,
        surfaces_json       LONGTEXT NULL,
        routing_metadata_json LONGTEXT NULL,
        created_at          VARCHAR(32) NOT NULL DEFAULT (CAST(UNIX_TIMESTAMP() AS CHAR)),
        updated_at          VARCHAR(32) NOT NULL DEFAULT (CAST(UNIX_TIMESTAMP() AS CHAR))
    )",
    "CREATE TABLE IF NOT EXISTS routing_rules (
        rule_id             VARCHAR(255) PRIMARY KEY,
        project_id          VARCHAR(255) NOT NULL,
        name                VARCHAR(255) NOT NULL,
        priority            INT NOT NULL DEFAULT 0,
        enabled             BOOLEAN NOT NULL DEFAULT TRUE,
        match_path          VARCHAR(255),
        match_model         VARCHAR(255),
        match_streaming     BOOLEAN,
        match_role          VARCHAR(255),
        match_headers       TEXT,
        min_prompt_tokens   INT,
        max_prompt_tokens   INT,
        deny_reason         TEXT,
        provider_order      TEXT,
        provider_weights    TEXT,
        timeout_secs        BIGINT,
        created_at          VARCHAR(32) NOT NULL DEFAULT (CAST(UNIX_TIMESTAMP() AS CHAR)),
        INDEX idx_routing_rules_project_id (project_id)
    )",
    "CREATE TABLE IF NOT EXISTS safety_policies (
        project_id          VARCHAR(255) PRIMARY KEY,
        mode                VARCHAR(64) NOT NULL,
        rules_json          TEXT,
        updated_at          VARCHAR(32) NOT NULL DEFAULT (CAST(UNIX_TIMESTAMP() AS CHAR))
    )",
    "CREATE TABLE IF NOT EXISTS semantic_policies (
        project_id          VARCHAR(255) PRIMARY KEY,
        version             VARCHAR(255) NOT NULL,
        enabled             BOOLEAN NOT NULL DEFAULT TRUE,
        entities_json       TEXT,
        topics_json         TEXT,
        updated_at          VARCHAR(32) NOT NULL DEFAULT (CAST(UNIX_TIMESTAMP() AS CHAR))
    )",
    "CREATE TABLE IF NOT EXISTS prompt_cache_routes (
        route_id            VARCHAR(255) PRIMARY KEY,
        project_id          VARCHAR(255) NOT NULL,
        cache_key           TEXT NOT NULL,
        provider_name       VARCHAR(255) NOT NULL,
        signal_kind         VARCHAR(32) NOT NULL DEFAULT 'warm',
        signal_strength     DOUBLE NOT NULL DEFAULT 1.0,
        observed_at_ms      BIGINT NOT NULL DEFAULT 0,
        expires_at_ms       BIGINT NOT NULL,
        INDEX idx_prompt_cache_routes_expires_at (expires_at_ms)
    )",
    "CREATE TABLE IF NOT EXISTS semantic_cache_entries (
        cache_id            VARCHAR(255) PRIMARY KEY,
        project_id          VARCHAR(255) NOT NULL,
        provider_name       VARCHAR(255) NOT NULL,
        model               VARCHAR(255) NOT NULL,
        tokens_json         LONGTEXT NOT NULL,
        response_status     INT NOT NULL,
        content_type        TEXT,
        response_body       LONGBLOB NOT NULL,
        prompt_tokens       BIGINT NOT NULL DEFAULT 0,
        created_at_ms       BIGINT NOT NULL,
        expires_at_ms       BIGINT NOT NULL,
        INDEX idx_semantic_cache_entries_expires_at (expires_at_ms),
        INDEX idx_semantic_cache_entries_created_at (created_at_ms)
    )",
    "CREATE TABLE IF NOT EXISTS project_tools (
        project_id          VARCHAR(255) NOT NULL,
        tool_name           VARCHAR(255) NOT NULL,
        description         TEXT,
        input_schema_json   TEXT NOT NULL,
        executor_kind       VARCHAR(64) NOT NULL,
        executor_config_json TEXT,
        enabled             BOOLEAN NOT NULL DEFAULT TRUE,
        timeout_ms          BIGINT,
        updated_at          VARCHAR(32) NOT NULL DEFAULT (CAST(UNIX_TIMESTAMP() AS CHAR)),
        PRIMARY KEY (project_id, tool_name),
        INDEX idx_project_tools_project_id (project_id)
    )",
    "CREATE TABLE IF NOT EXISTS project_prompts (
        project_id          VARCHAR(255) NOT NULL,
        prompt_name         VARCHAR(255) NOT NULL,
        version             VARCHAR(255) NOT NULL,
        environment         VARCHAR(255) NOT NULL,
        description         TEXT,
        target              VARCHAR(64) NOT NULL,
        template_text       TEXT NOT NULL,
        variables_schema_json TEXT,
        rollout_metadata_json TEXT,
        active              BOOLEAN NOT NULL DEFAULT TRUE,
        updated_at          VARCHAR(32) NOT NULL DEFAULT (CAST(UNIX_TIMESTAMP() AS CHAR)),
        PRIMARY KEY (project_id, prompt_name, version),
        INDEX idx_project_prompts_project_id (project_id),
        INDEX idx_project_prompts_name (project_id, prompt_name)
    )",
    "CREATE TABLE IF NOT EXISTS project_rollout_policies (
        project_id          VARCHAR(255) NOT NULL,
        policy_name         VARCHAR(255) NOT NULL,
        description         TEXT,
        gate_config_json    TEXT NOT NULL,
        target_environment  VARCHAR(255),
        updated_at          VARCHAR(32) NOT NULL DEFAULT (CAST(UNIX_TIMESTAMP() AS CHAR)),
        PRIMARY KEY (project_id, policy_name),
        INDEX idx_project_rollout_policies_project_id (project_id)
    )",
    "CREATE TABLE IF NOT EXISTS project_prompt_rollouts (
        project_id          VARCHAR(255) NOT NULL,
        prompt_name         VARCHAR(255) NOT NULL,
        rollout_id          VARCHAR(255) NOT NULL,
        policy_name         VARCHAR(255) NOT NULL,
        baseline_version    VARCHAR(255),
        candidate_version   VARCHAR(255) NOT NULL,
        baseline_run_id     VARCHAR(255) NOT NULL,
        candidate_run_id    VARCHAR(255) NOT NULL,
        target_environment  VARCHAR(255),
        status              VARCHAR(64) NOT NULL,
        recommendation_action VARCHAR(64),
        comparison_json     LONGTEXT NOT NULL,
        created_at          VARCHAR(32) NOT NULL DEFAULT (CAST(UNIX_TIMESTAMP() AS CHAR)),
        applied_at          VARCHAR(32),
        PRIMARY KEY (project_id, prompt_name, rollout_id),
        INDEX idx_project_prompt_rollouts_prompt (project_id, prompt_name)
    )",
    "CREATE TABLE IF NOT EXISTS project_datasets (
        project_id          VARCHAR(255) NOT NULL,
        dataset_name        VARCHAR(255) NOT NULL,
        description         TEXT,
        schema_json         TEXT,
        updated_at          VARCHAR(32) NOT NULL DEFAULT (CAST(UNIX_TIMESTAMP() AS CHAR)),
        PRIMARY KEY (project_id, dataset_name),
        INDEX idx_project_datasets_project_id (project_id)
    )",
    "CREATE TABLE IF NOT EXISTS project_dataset_items (
        project_id          VARCHAR(255) NOT NULL,
        dataset_name        VARCHAR(255) NOT NULL,
        item_id             VARCHAR(255) NOT NULL,
        input_json          TEXT NOT NULL,
        expected_output_json TEXT,
        metadata_json       TEXT,
        updated_at          VARCHAR(32) NOT NULL DEFAULT (CAST(UNIX_TIMESTAMP() AS CHAR)),
        PRIMARY KEY (project_id, dataset_name, item_id),
        INDEX idx_project_dataset_items_dataset (project_id, dataset_name)
    )",
    "CREATE TABLE IF NOT EXISTS project_eval_runs (
        run_id               VARCHAR(255) PRIMARY KEY,
        project_id           VARCHAR(255) NOT NULL,
        dataset_name         VARCHAR(255) NOT NULL,
        target_url           TEXT NOT NULL,
        status               VARCHAR(64) NOT NULL,
        total_items          INT NOT NULL DEFAULT 0,
        passed_items         INT NOT NULL DEFAULT 0,
        failed_items         INT NOT NULL DEFAULT 0,
        total_input_tokens   BIGINT NOT NULL DEFAULT 0,
        total_output_tokens  BIGINT NOT NULL DEFAULT 0,
        total_cost           DOUBLE NOT NULL DEFAULT 0.0,
        average_latency_ms   DOUBLE NOT NULL DEFAULT 0.0,
        summary_json         TEXT,
        created_at           VARCHAR(32) NOT NULL DEFAULT (CAST(UNIX_TIMESTAMP() AS CHAR)),
        completed_at         VARCHAR(32) NULL,
        INDEX idx_project_eval_runs_project_id (project_id),
        INDEX idx_project_eval_runs_dataset (project_id, dataset_name)
    )",
    "CREATE TABLE IF NOT EXISTS project_eval_run_items (
        run_id               VARCHAR(255) NOT NULL,
        project_id           VARCHAR(255) NOT NULL,
        dataset_name         VARCHAR(255) NOT NULL,
        item_id              VARCHAR(255) NOT NULL,
        passed               BOOLEAN NOT NULL DEFAULT FALSE,
        status_code          INT NULL,
        latency_ms           BIGINT NOT NULL DEFAULT 0,
        output_text          TEXT,
        evaluation_json      TEXT,
        error                TEXT,
        input_tokens         BIGINT NOT NULL DEFAULT 0,
        output_tokens        BIGINT NOT NULL DEFAULT 0,
        cost                 DOUBLE NOT NULL DEFAULT 0.0,
        created_at           VARCHAR(32) NOT NULL DEFAULT (CAST(UNIX_TIMESTAMP() AS CHAR)),
        PRIMARY KEY (run_id, item_id),
        INDEX idx_project_eval_run_items_run_id (project_id, run_id)
    )",
    "CREATE TABLE IF NOT EXISTS governance_history (
        change_id           VARCHAR(255) PRIMARY KEY,
        project_id          VARCHAR(255) NOT NULL,
        resource_type       VARCHAR(64) NOT NULL,
        resource_id         VARCHAR(255) NOT NULL,
        action              VARCHAR(64) NOT NULL,
        before_json         TEXT,
        after_json          TEXT,
        changed_at          VARCHAR(32) NOT NULL DEFAULT (CAST(UNIX_TIMESTAMP() AS CHAR)),
        INDEX idx_governance_history_project_id (project_id),
        INDEX idx_governance_history_resource_type (project_id, resource_type)
    )",
];
